server:
  port: 83

spring:
  application:
    name: consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server-url:
  nacos-user-service: http://cloud-nacos-provider
