server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer

  rabbitmq:
    host: 121.36.218.11
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders: #配置要绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称，用于binding集合
          type: rabbit #消息组件的类型
          enviroment: #rabbitmq的相关环境配置
            spring:
      #              rabbitmq:
      #                host: 121.36.218.11
      #                port: 5672
      #                username: guest
      #                password: guest

      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #使用的exchange名称的定义
          content-type: application/json #消息类型
          binder: defaultRabbit #设置要绑定消息服务的具体设置
          group: G1 #分组

eureka:
  client:
    service-url:
      #设置与eureka server的交互的地址查询服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8802.com
    prefer-ip-address: true