server:
  port: 2001

spring:
  application:
    name: seata-order-service

  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group


    nacos:
      discovery:
        server-addr: 192.168.0.149:3333


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.218.11:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

feign:
  sentinel:
    enabled: true
logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cm.example.domain


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: fsp_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 192.168.0.149:3333
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.0.149:3333
      namespace:
      userName: "nacos"
      password: "nacos"
      group: SEATA_GROUP

